name: "Kubernetes deploy wordpress"

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: igorira
  CLUSTER_NAME: aks-eesdevops
  CLUSTER_RESOURCE_GROUP: rg-eesdevops-dev-main
  NAMESPACE: eesdevops-namespace
  SECRET: wordpress-cr
  APP_NAME: wordpressapp
  BUILD_FILE: ./
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
        
    - name: Deploy app controller to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ./kustomization.yaml
          ./mysql-deployment.yaml
          ./wordpress-deployment.yaml
        namespace: ${{ env.NAMESPACE }}
        